### ISSUE TITLE
Metrics list

### ISSUE THREAD

**Issue by dbmtrde** [kic68/downdetector-exporter#2]
Hi All,
can you possibly document which metrics can be collected with this exporter?
Maybe also provide a docker image?
best regards

**Comment by kic68** [comment]
Hey @dbmtrde ,

sorry, this escaped my attention due to a stressful move this summer.

Thanks to @nohn the image is now available.
The exporter is now exporting 
```
	fieldsToReturn       = []string{"id", "name", "slug", "baseline_current", "country_iso", "stats_24", "stats_60", "status"}
```

Best!
Kic
